config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/observer', as: 'rails_admin'
  devise_for :users

  root 'home#index'
  post 'contact' => 'home#contact'
  resources :tasks do
    member{
      get :assign
      get :assign_user
    }
  end
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user#.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :user_task_maps
  has_many :users,through: :user_task_maps
  validates :name,:description,:start_date,:end_date,:priority,presence: true
  def self.candidate_set
    user_list=User.where(id: ((User.all.pluck(:id)) - 
      (UserTaskMap.where('created_at > ?', (Date.today) - 1.day)).pluck(:user_id)) 
    ) 
    if user_list.count==0
      user_list = User.all
    end
    repo_threshold=user_list.order(reputation: :desc).first.reputation.to_i
    best_fit=user_list.where(reputation: ((repo_threshold/2)..repo_threshold)).order(last_sign_in_at: :desc)
    if best_fit.count.zero?
      best_fit=user_list.order(last_sign_in_at: :desc)
    end
    best_fit 
  end

  # active_weight = Last Seen
  # reputation_point = Score as per his activity
  # List of people having high
  # These users are weighted in increasing order
  def best_person_for_the_task
    best_fit=Task.candidate_set - users
    if best_fit.count==0 && users.pluck(:id).count.zero?
      best_fit = User.all.order(last_sign_in_at: :desc)
    end
    best_fit.first
  end
  def is_person_feasible?(user) # Is Person Available
    
  end
  def objective?
    
  end
  def solution?
    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email,presence: true
  has_paper_trail  
  has_many :user_task_maps
  has_many :tasks,through: :user_task_maps  
end

app/models/user_task_map.rb
class UserTaskMap < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  validates :user_id,:task_id,presence: true
  validates :user_id,uniqueness: {scope: :task_id,message: ' can work only once on a task.'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact
    if params[:email].present? && params[:name].present? && params[:message].present?
      Notifier.notify(params[:email],params[:name],params[:message]).deliver_now!
      flash[:info] = "Thanks for contacting us." 
      redirect_to root_path
    else
      flash[:warning] = "Please provide your detail and proper message." 
      redirect_to root_path
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_task,only: [:show,:edit,:update,:assign,:assign_user]
  def create
    if current_user.is_admin
      task=(@task ? @task : Task.new(task_params))
      if @task
        task.assign_attributes(task_params)
      end
      if task.valid?
        task.save
        flash.now['info']="Task has been #{@task ? 'updated' : 'created'} successfully."
        redirect_to tasks_path
      else
        flash.now['danger']="Task was not be #{@task ? 'updated' : 'created'} because of following errors.\n #{task.errors.full_messages.uniq.join(' & ')}"
        @task=task
        render 'new'
      end
    end
  end
  def assign
    @best_fit=@task.best_person_for_the_task
    @alternate_fit=Task.candidate_set.first(7)
  end
  def assign_user
    user_task_map=@task.user_task_maps.build(user_id: params[:user])
    if user_task_map.valid?
      user_task_map.save
      flash['info']="Task has been successfully assigned to user #{params[:user]}."
      redirect_to assign_task_path(@task)
    else
      flash['danger']="Task was not assigned to user #{params[:user]} because #{user_task_map.errors.full_messages.uniq.join(' & ')}"
      redirect_to assign_task_path(@task)
    end
  end
  def update
    create
  end
  def index
    @tasks=Task.all.order(id: :desc)
  end
  def edit
    render 'new'
  end
  private
  def task_params
    params.require(:task).permit(:name,:description,
      :start_date,:end_date,:priority)
  end
  def get_task
    if current_user.is_admin
      @task=Task.find(params[:id])
    else
      @task=current_user.tasks.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
/ Banner
%section#banner
  %h2
    %strong User Task
    is a user task mapping according to Greedy Algo
  %p Brought to you by DimoMohit
  %ul.actions
    %li
      =link_to 'Get started',new_user_session_path,class: 'button special'
/ One
%section#one.wrapper.special
  .inner
    %header.major
      %h2 Lorem ipsum feugiat tempus
    .features
      .feature
        %i.fa.fa-diamond
        %h3 Etiam consequat
        %p Sed tempus feugiat adipiscing nisl cursus aliquam dolore.
      .feature
        %i.fa.fa-copy
        %h3 Sed adipiscing
        %p Sed tempus feugiat adipiscing nisl cursus aliquam dolore.
      .feature
        %i.fa.fa-paper-plane-o
        %h3 Feugiat nullam
        %p Sed tempus feugiat adipiscing nisl cursus aliquam dolore.
      .feature
        %i.fa.fa-save
        %h3 Amet imperdiet
        %p Sed tempus feugiat adipiscing nisl cursus aliquam dolore.
      .feature
        %i.fa.fa-envelope-o
        %h3 Tempus lorem
        %p Sed tempus feugiat adipiscing nisl cursus aliquam dolore.
/ Two
%section#contact-us.wrapper.style2.special
  .inner.narrow
    %header
      %h2 Get in touch
    =form_tag contact_path ,html: {class: 'grid-form'} do |f|
      .form-control.narrow
        %label{:for => "name"} Name
        =text_field_tag :name,'',id: :name
      .form-control.narrow
        %label{:for => "email"} Email
        =email_field_tag :email,'',id: :email
      .form-control
        %label{:for => "message"} Message
        =text_area_tag :message,'',id: :message
      %ul.actions
        %li
          =submit_tag 'Send Message'

%footer#footer
  .copyright
    \&copy; Untitled. Design:
    
      
/ Scripts

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UserTask
    %meta{:charset => "utf-8"}
    %meta{"http-equiv"=>"X-UA-Compatible" ,:content=>"IE=edge"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    /[if lte IE 8]
      =javascript_include_tag 'ie/html5shiv',cache: true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true,cache: true
    = csrf_meta_tags
    /[if lte IE 9]
      =stylesheet_link_tag    'ie9', media: 'all', 'data-turbolinks-track' => true,cache: true
  %body
    
    / Header
    %header#header.alt
      %h1
        =link_to 'UserTask',root_path
      =link_to "Menu",'#nav'
    / Nav
    %nav#nav
      %ul.links
        %li
          =link_to 'Home',root_path
        -if current_user && current_user.is_admin
          %li
            =link_to 'Observer',rails_admin.dashboard_path
          %li
            =link_to 'Create Task',new_task_path
        -if current_user
          %li
            =link_to 'Tasks',tasks_path
        -else
          %li
            =link_to 'Sign Up',new_user_registration_path
          %li
            =link_to 'Login',new_user_session_path
        %li
          =link_to 'Contact Us','/#contact-us'
    - flash.each do |name, msg|
      -flash_name = (name!='error' ? name : 'danger')
      = content_tag :div, msg, :id => "flash_#{flash_name}",class: "alert alert-dismissible alert-#{flash_name} m-t-50"
      .clear_both
    .clear_both 
    = yield
    %section.header
    - if Rails.env == 'development'
      = javascript_include_tag 'application',cache: true
    -else
      = javascript_include_tag 'application',cache: true,async: true

app/views/notifier/notify.html.haml
.div{style: "float:none;"}
  %h4
    Thanks for contacting me.
.div
  %p Hi #{@name}
  %p I have received your message '#{@message}' through #{@root_url}.
.div
  %p Thanks and regards,
  %p Mohit
  %p Email : dimomohit@gmail.com

app/views/tasks/assign.html.haml
%section#two.wrapper.style2.special
  .inner.narrow
    %header
      %h2
        =@task.name
    .row
      .col-xs-5.col-sm-4
        Description
      .col-xs-7.col-sm-8
        #{@task.description}
    .row
      .col-xs-5.col-sm-4
        Priority
      .col-xs-7.col-sm-8
        #{@task.priority}
    .row
      .col-xs-5.col-sm-4
        Start Date
      .col-xs-7.col-sm-8
        #{@task.start_date}
    .row
      .col-xs-5.col-sm-4
        End Date
      .col-xs-7.col-sm-8
        #{@task.end_date}
    %header.m-t-50
      %h2
        Suggested Person
  .container.center
    .feature.center
      %i.fa.fa-user
      %h3 #{@best_fit.name}
      %p #{@best_fit.email}
      %p Has Worked on #{@best_fit.user_task_maps.count} Tasks
      =link_to 'Save',assign_user_task_path(@task,user: @best_fit.id),class: 'button special'
    %header.m-t-50
      %h2
        Other Nearest Alternatives
  .container.center
    .features
      -(@alternate_fit - [@best_fit]).each do |user|
        .feature
          %i.fa.fa-user
          %h3 #{user.name}
          %p #{user.email}
          %p Has Worked on #{user.user_task_maps.count} Tasks
          =link_to 'Assign',assign_user_task_path(@task,user: user.id),class: 'button special'

app/views/tasks/index.html.haml
%section.wrapper.special.style2
  .inner
    %header.major
      %h2 Task List
    .features
      -@tasks.each do |task|
        .feature
          =link_to task_path(task) do
            %i.fa.fa-diamond
            %h3 #{task.name}
            %p #{task.description}
            %p Done by #{task.users.count} Users

app/views/tasks/new.html.haml
%section#two.wrapper.style2.special
  .inner.narrow
    %header
      %h2
        Create New Task
    = form_for(@task||Task.new, html: { method: ((@task && @task.id) ? :patch : :post) }) do |f|
      / = devise_error_messages!
      .form-control
        = f.label :name
        %br/
        = f.text_field :name, autofocus: true
      .form-control
        = f.label :description
        %br/
        = f.text_field :description, autofocus: true
      .form-control
        = f.label :start_date
        %br/
        = f.date_field :start_date, autofocus: true
      .form-control
        = f.label :end_date
        %br/
        = f.date_field :end_date, autofocus: true
      .form-control
        = f.label :priority
        %br/
        = f.number_field :priority,min: 0,max: 5, autofocus: true
      .actions
        = f.submit "Create"

app/views/tasks/show.html.haml
%section#two.wrapper.style2.special
  .inner.narrow
    %header
      %h2
        =@task.name
    .row
      .col-xs-5.col-sm-4
        Description
      .col-xs-7.col-sm-8
        #{@task.description}
    .row
      .col-xs-5.col-sm-4
        Priority
      .col-xs-7.col-sm-8
        #{@task.priority}
    .row
      .col-xs-5.col-sm-4
        Start Date
      .col-xs-7.col-sm-8
        #{@task.start_date}
    .row
      .col-xs-5.col-sm-4
        End Date
      .col-xs-7.col-sm-8
        #{@task.end_date}
    -if current_user.is_admin
      .row
        .col-xs-12
          =link_to 'Auto Assign Task',assign_task_path(@task),class: 'button special'
    %header.m-t-50
      %h2
        Worked by
  .container
    .features
      -@task.user_task_maps.each do |user_task_map|
        .feature
          %i.fa.fa-user
          %h3 #{user_task_map.user.name}
          %p #{user_task_map.user.email}
          %p Worked on #{user_task_map.created_at.strftime('%d %M %Y')}